version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9515:9515"
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME=
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://0.0.0.0
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=ssl
    networks:
      - laravel
    command: >
      sh -c "php artisan key:generate && php artisan serve --host 0.0.0.0 --port 8000"

networks:
  laravel:

